# Generated by Django 2.1.7 on 2019-03-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('message', models.CharField(max_length=300)),
            ],
        ),
    ]
